name: slee_fi
description: A Sleep to Earn Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  easy_localization: ^3.0.1
  flutter_svg: ^1.1.1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  dartz: ^0.10.1
  logger: ^1.1.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  cached_network_image: ^3.2.1
  fl_chart: ^0.55.0
  flutter_date_pickers: ^0.4.0
  flutter_screenutil: ^5.5.3+2
  pin_code_fields: ^7.4.0
  loop_page_view: ^1.2.0
  smooth_page_indicator: ^1.0.0+2
  tab_indicator_styler: ^2.0.0
  percent_indicator: ^4.2.2
  dropdown_button2: ^1.6.2
  qr_flutter: ^4.0.0
  cool_dropdown: ^1.4.1
  url_launcher: ^6.1.4
  syncfusion_flutter_sliders: ^20.1.61
  syncfusion_flutter_datepicker: ^20.1.61
  pie_chart: ^5.3.1
  pull_to_refresh: ^2.0.0
  recase: ^4.0.0
  jiffy: ^5.0.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  web3dart: 2.3.5
  erc20: ^1.0.0
  eip55: ^1.0.2
  local_auth: ^2.1.0
  get_storage: ^2.0.3
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  flutter_secure_storage: ^5.0.2
  web_socket_channel: ^2.2.0
  copy_with_extension: ^4.0.2
  decimal: ^2.2.0
  path_provider: ^2.0.11
  fluttertoast: ^8.0.9
  flutter_phoenix: ^1.0.0
  mobile_scanner: ^2.0.0
  appsflyer_sdk: ^6.5.2+2
  card_swiper: ^2.0.4
  safe_device: ^1.1.1
  permission_handler: ^9.2.0
  ethereum_addresses: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1
  flutter_launcher_icons: ^0.9.3
  isar_generator: ^2.5.0
  copy_with_extension_gen: ^4.0.2
  test: ^1.21.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/crypto_icons/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Italic.ttf