name: slee_fi
description: A Sleep to Earn Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_translate_annotations: ^2.1.0
  flutter_translate: ^4.0.2
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  dartz: ^0.10.1
  logger: ^1.1.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  widgetbook_annotation: ^2.0.2
  cached_network_image: 3.2.0
  fl_chart: ^0.50.6
  flutter_date_pickers: ^0.3.0
  flutter_screenutil: ^5.5.3
  pin_code_fields: ^7.4.0
  loop_page_view: ^1.1.1

dependency_overrides:
  analyzer: ^4.1.0

dev_dependencies:

  flutter_lints: 1.0.4
  flutter_translate_gen: ^2.2.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1
  widgetbook: ^2.2.1
  widgetbook_generator: ^2.1.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/i18n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
