name: slee_fi
description: A Sleep to Earn Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  easy_localization: ^3.0.1
  flutter_svg: ^1.1.1+1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  dartz: ^0.10.1
  logger: ^1.1.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  cached_network_image: ^3.2.1
  fl_chart: ^0.55.0
  flutter_date_pickers: ^0.4.0
  flutter_screenutil: ^5.5.3+2
  pin_code_fields: ^7.4.0
  loop_page_view: ^1.2.0
  smooth_page_indicator: ^1.0.0+2
  tab_indicator_styler: ^2.0.0
  percent_indicator: ^4.2.2
  dropdown_button2: ^1.6.3
  qr_flutter: ^4.0.0
  cool_dropdown: ^1.4.2
  url_launcher: ^6.1.5
  syncfusion_flutter_sliders: ^20.2.40
  syncfusion_flutter_datepicker: ^20.2.40
  pie_chart: ^5.3.2
  pull_to_refresh: ^2.0.0
  recase: ^4.0.0
  jiffy: ^5.0.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  web3dart: 2.3.5
  erc20: ^1.0.0
  eip55: ^1.0.2
  local_auth: ^2.1.0
  get_storage: ^2.0.3
  isar: ^2.5.0
  image_gallery_saver: ^1.7.1
  isar_flutter_libs: ^2.5.0
  flutter_secure_storage: ^5.0.2
  web_socket_channel: ^2.2.0
  copy_with_extension: ^4.0.2
  decimal: ^2.2.0
  path_provider: ^2.0.11
  fluttertoast: ^8.0.9
  mobile_scanner: ^2.0.0
  appsflyer_sdk: ^6.5.2+2
  card_swiper: ^2.0.4
  safe_device: ^1.1.1
  ethereum_addresses: ^1.0.2
  permission_handler: 9.2.0
  focus_detector: ^2.0.1
  eth_sig_util: ^0.0.9
  top_snackbar_flutter: ^2.1.1
  connectivity_plus: ^2.3.6
  flutter_native_splash: ^2.2.6
  webview_flutter: ^3.0.4
  lottie: ^1.3.0
  sentry: ^6.8.0
  sentry_flutter: ^6.8.0
  device_info_plus: ^4.0.0
  intl: ^0.17.0
  external_app_launcher: ^3.0.0
  flutter_background_service: ^2.1.3
  flutter_foreground_task: ^3.8.1
  screenshot: ^1.2.3
  social_share: ^2.2.1
  just_audio: ^0.9.28
  health:
    git:
      url: https://github.com/Sotatek-ThangBui/health.git
      ref: master

dependency_overrides:
  analyzer: ^4.2.0
  xml: ^6.1.0
#  package_info_plus: ^1.4.2
#  package_info_plus_windows: ^1.0.5
#  ffi: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4
  retrofit_generator: ^4.0.3
  flutter_launcher_icons: ^0.9.3
  isar_generator: ^2.5.0
  copy_with_extension_gen: ^4.0.2
  test: ^1.21.4
  dart_code_metrics: ^4.16.0
  numeral: ^2.0.1
  flutter_flavorizr: ^2.1.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/crypto_icons/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/json/
    - assets/sounds/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Italic.ttf

flavorizr:
  app:
    android:
      flavorDimensions: "SleeFi"
    ios:

  instructions:
    - assets:download
    - assets:extract
    - android:androidManifest
    - android:buildGradle
    - android:dummyAssets
    - android:icons
    #    - flutter:flavors
    #    - flutter:app
    #    - flutter:pages
    - flutter:targets
    #    - ios:xcconfig
    - ios:buildTargets
    #    - ios:schema
    #    - ios:dummyAssets
    #    - ios:icons
    - ios:plist
    #    - ios:launchScreen
    #    - google:firebase
    - assets:clean
    - ide:config

  flavors:
    dev:
      app:
        name: "SleeFi Dev"

      android:
        applicationId: "com.sotatek.slee_fi"
      ios:
        bundleId: "com.sotatek.slee_fi"

    stg:
      app:
        name: "SleeFi Stg"

      android:
        applicationId: "com.sotatek.slee_fi"
      ios:
        bundleId: "com.sotatek.slee_fi"