name: slee_fi
description: A Sleep to Earn Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  easy_localization: ^3.0.1
  flutter_svg: ^1.1.1+1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  dartz: ^0.10.1
  logger: ^1.1.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  cached_network_image: ^3.2.1
  fl_chart: ^0.55.0
  flutter_date_pickers: ^0.4.0
  flutter_screenutil: ^5.5.3+2
  pin_code_fields: ^7.4.0
  loop_page_view: ^1.2.0
  smooth_page_indicator: ^1.0.0+2
  tab_indicator_styler: ^2.0.0
  percent_indicator: ^4.2.2
  dropdown_button2: ^1.6.3
  qr_flutter: ^4.0.0
  cool_dropdown: ^1.4.1
  url_launcher: ^6.1.5
  syncfusion_flutter_sliders: ^20.2.38
  syncfusion_flutter_datepicker: ^20.2.38
  pie_chart: ^5.3.2
  pull_to_refresh: ^2.0.0
  recase: ^4.0.0
  jiffy: ^5.0.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  web3dart: 2.3.5
  erc20: ^1.0.0
  eip55: ^1.0.2
  local_auth: ^2.1.0
  get_storage: ^2.0.3
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  flutter_secure_storage: ^5.0.2
  web_socket_channel: ^2.2.0
  copy_with_extension: ^4.0.2
  decimal: ^2.2.0
  path_provider: ^2.0.11
  fluttertoast: ^8.0.9
  mobile_scanner: ^2.0.0
  appsflyer_sdk: ^6.5.2+2
  card_swiper: ^2.0.4
  safe_device: ^1.1.1
  ethereum_addresses: ^1.0.2
  permission_handler: 9.2.0
  focus_detector: ^2.0.1
  eth_sig_util: ^0.0.9
  top_snackbar_flutter: ^2.1.1
  connectivity_plus: ^2.3.5
  flutter_native_splash: ^2.2.4
  webview_flutter: ^3.0.4
  device_info_plus: ^4.0.0
  intl: ^0.17.0
  fetch_health_data:
    git:
      url: https://github.com/Sotatek-ThangBui/fetch_health_data.git
      ref: master

dependency_overrides:
  analyzer: ^4.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  freezed: ^2.0.5
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  injectable_generator: ^1.5.3
  retrofit_generator: ^4.0.2
  flutter_launcher_icons: ^0.9.3
  isar_generator: ^2.5.0
  copy_with_extension_gen: ^4.0.2
  test: ^1.21.4
  dart_code_metrics: ^4.16.0
  numeral: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/crypto_icons/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Italic.ttf