name: Analyze

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  flutter-analyze:
    runs-on: ubuntu-latest
    outputs:
      diawi_url: ${{ steps.diawi_url.outputs.result }}
      diawi_qrcode: ${{ steps.diawi_qrcode.outputs.result }}

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          channel: 'stable'

      - run: flutter --version

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze