name: Build APK, Upload Diawi, Send GG Chat Noti

on:
  push:
    branches: [ build ]

jobs:
  build-apk:
    uses: ./.github/workflows/build_apk.yml
    secrets:
      diawi_token: ${{ secrets.DIAWI_TOKEN }}

  noti-gg-chat:
    needs: build-apk
    uses: ./.github/workflows/google_chat_msg.yml
    secrets:
      webhook: ${{ secrets.GGCHATWEBHOOK }}
    with:
      imageUrl: ${{ needs.build-apk.outputs.diawi_qrcode }}
      url: ${{ needs.build-apk.outputs.diawi_url }}
