name: Reusable Build APK and Upload Diawi

on:
  workflow_call:
    secrets:
      diawi_token:
        required: true
    outputs:
      diawi_url:
        value: ${{ jobs.build.outputs.diawi_url }}
      diawi_qrcode:
        value: ${{ jobs.build.outputs.diawi_qrcode }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      diawi_url: ${{ steps.diawi_url.outputs.result }}
      diawi_qrcode: ${{ steps.diawi_qrcode.outputs.result }}

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          channel: 'stable'

      - run: flutter --version

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Build Release APK
        id: apk
        run: flutter build apk

      - name: Upload Diawi
        uses: rnkdsh/action-upload-diawi@v1.2.5
        id: diawi
        with:
          token: ${{ secrets.diawi_token }}
          file: build/app/outputs/flutter-apk/app-release.apk

      - name: Set Diawi Url
        id: diawi_url
        run: echo "::set-output name=result::${{ steps.diawi.outputs.url }}"

      - name: Set Diawi QRCode
        id: diawi_qrcode
        run: echo "::set-output name=result::${{ steps.diawi.outputs.qrcode }}"