# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ build ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    name: Build APK and upload to Diawi
    runs-on: ubuntu-latest
    outputs:
      diawi_url: ${{ steps.diawi_url.outputs.result }}
      diawi_qrcode: ${{ steps.diawi_qrcode.outputs.result }}

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          channel: 'stable'
      - run: flutter --version

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze

      - name: Build Release APK
        id: apk
        run: flutter build apk

      - name: Upload Diawi
        uses: rnkdsh/action-upload-diawi@v1.2.5
        id: diawi
        with:
          token: ${{ secrets.DIAWI_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk

      - name: Set Diawi Url
        id: diawi_url
        run: echo "::set-output name=result::${{ steps.diawi.outputs.url }}"

      - name: Set Diawi QRCode
        id: diawi_qrcode
        run: echo "::set-output name=result::${{ steps.diawi.outputs.qrcode }}"

  notification:
    name: Google Chat Notification
    runs-on: ubuntu-latest
    needs: build

    steps:
      - run: echo "${{ needs.build.outputs.diawi_url }}"
      - run: echo "${{ needs.build.outputs.diawi_qrcode }}"
      - name: Google Chat Notification
        run: |
          curl --location --request POST '${{ secrets.GGCHATWEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '
          {
              "cards": [
                  {
                      "sections": [
                          {
                              "widgets": [
                                  {
                                      "image": {
                                          "imageUrl": "${{ needs.build.outputs.diawi_qrcode }}",
                                          "onClick": {
                                              "openLink": {
                                                  "url": "${{ needs.build.outputs.diawi_url }}"
                                              }
                                          }
                                      }
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }'
