name: Send GG Chat

on:
  workflow_call:
    secrets:
      webhook:
        required: true
    inputs:
      diawi_qr:
        required: false
        type: string
      diawi_url:
        required: true
        type: string
#      deploygate_url:
#        required: false
#        type: string
#      deploygate_icon:
#        required: true
#        type: string

jobs:
  send-message:
    name: Send Msg
    runs-on: ubuntu-latest
    steps:
      - name: Submit string
        run: |
          echo ${{ inputs }}

      - name: Google Chat Notification
        run: |
          curl --location --request POST '${{ secrets.webhook }}' \
          --header 'Content-Type: application/json' \
          --data-raw '
          {
            "cards": [
              {
                "sections": [
                  {
                    "header": "Diawi",
                    "widgets": [
                      {
                        "image": {
                          "imageUrl": "${{ inputs.diawi_qr }}",
                          "onClick": {
                            "openLink": {
                              "url": "${{ inputs.diawi_url }}"
                            }
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }'