name: Reusable Send Notification

on:
  workflow_call:
    secrets:
      webhook:
        required: true
    inputs:
      imageUrl:
        required: false
        type: string
      url:
        required: true
        type: string

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.imageUrl }}"
      - run: echo "${{ inputs.url }}"
      - name: Google Chat Notification
        run: |
          curl --location --request POST '${{ secrets.webhook }}' \
          --header 'Content-Type: application/json' \
          --data-raw '
          {
              "cards": [
                  {
                      "sections": [
                          {
                              "widgets": [
                                  {
                                      "image": {
                                          "imageUrl": "${{ inputs.imageUrl }}",
                                          "onClick": {
                                              "openLink": {
                                                  "url": "${{ inputs.url }}"
                                              }
                                          }
                                      }
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }'
